[package]
name = "timestamp"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "moveos/moveos-stdlib/move-stdlib", rev = "main" }
MoveosStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "moveos/moveos-stdlib/moveos-stdlib", rev = "main" }
RoochFramework = { git = "https://github.com/rooch-network/rooch.git", subdir = "crates/rooch-framework", rev = "main" }

[addresses]
timestamp = "0x5786c6684eb9d8587d8f7f21000195f14b00f21f44c65368d58382dddfb14926"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"

[dev-addresses]
timestamp = "0x42"